config/routes.rb
Rails.application.routes.draw do
  root to: "pages#home"
  get "formations", to: "pages#formations"
  get "experiences", to: "pages#experiences"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home; end
  def experiences; end
  def formations; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="https://github.com/Satomishi"><i class="fab fa-github"></i></a>
    <a href="https://www.linkedin.com/in/olivierkermoal/"><i class="fab fa-linkedin"></i></a>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid justify-content-between p-0">
    <% if current_page?(root_path) %>
      <%= link_to "A propos", root_path, class: "nav-link active-link" %>
    <% else %>
      <%= link_to "A propos", root_path, class: "nav-link" %>
    <% end %>
    <% if current_page?(formations_path) %>
      <%= link_to "Formations", formations_path, class: "nav-link active-link" %>
    <% else %>
      <%= link_to "Formations", formations_path, class: "nav-link" %>
    <% end %>
    <% if current_page?(experiences_path) %>
      <%= link_to "Expériences", experiences_path, class: "nav-link active-link" %>
    <% else %>
      <%= link_to "Expériences", experiences_path, class: "nav-link" %>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Portfolio</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <script src="https://cdn.jsdelivr.net/npm/typed.js@2.0.12"></script>
  </head>

  <body>
    <div class="app-grid">
      <div>
        <%= render 'layouts/navbar' %>
      </div>
      <div style='overflow-y:scroll; position:relative;'>
        <%= yield %>
      </div>
      <div>
        <%= render 'layouts/footer' %>
      </div>
    </div>
  </body>
</html>

app/views/pages/formations.html.erb
<h2>Le Wagon batch #1019 - 2022</h2>
<p>Compétences techniques : Ruby, Ruby on Rails, PostgreSQL, ES6, HTML/CSS/Bootstrap,
Stimulus JS, wireframing avec Figma et service tier tel que Heroku, Cloudinary etc...
Compétences mises en application au travers de projets (un clone de AirBnB et un projet
de groupe original).</p>
<h2><b>→ Obtention de la certification concepteur - développeur d’application web (RNCP 6)</b></h2>

app/views/pages/home.html.erb
<div class="container container-title">
  <div class="info-title">
    <h3>Bonjour et bienvenu sur mon site !<br><span data-controller="type"></span></h3>
    <p>Développeur web full stack, avec une préférence pour le back-end. Je suis curieux de nature
    et en soif constant d'apprentissage et de découverte. Je souhaite canaliser cette énergie dans
    un projet d'envergure.</p>
  </div>
</div>